# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TGIaFZY1x3qabN-6fBMrDYv2en0FtP5
"""

import sklearn
import numpy as np
from sklearn.neural_network import MLPClassifier

import pandas
df = pandas.read_csv('data_final_with_output_presets.csv')
#print()
#Input array
X=np.array(df[['Avg.PCC','Avg.Motion','averageintensitycomparision','Scene.Count','Frames.per.Second','Original.Bitrate','Width','Height']])

#Output
y=np.array(df[['Compression.Preset']])
#X = np.random.randint(1,10,size = (100,8))
#y = np.random.choice([0,1],size = (100))
print(X)
print(y)

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(10,5,5,2), random_state=1)

clf.fit(X, y)

y_pred = clf.predict(X)

error = np.mean(abs(y_pred - y))
error